import { z } from "zod";

export const treatmentCertificateSchema = z.object({
  hideLetterhead: z.boolean().optional().default(false),
  serialNo: z.string().optional().default(""),
  dateIssued: z.coerce.date().nullable().optional(),
  certificateNo: z.string().optional().default(""),
  treatmentProviderId: z.string().optional().default("ID0018MB"),
  relatedDocumentNo: z.string().optional().default(""),
  containers: z.string().optional().default(""),
  consigneeName: z.string().optional().default(""),
  consigneeAddress: z.string().optional().default(""),
  notifyParty: z.string().optional().default(""),
  sealNumbers: z.string().optional().default(""),
  carrierVessel: z.string().optional().default(""),
  clientName: z.string().optional().default(""),
  clientAddress: z.string().optional().default(""),
  commodity: z.string().optional().default(""),
  grossWeight: z.string().optional().default(""),
  netWeight: z.string().optional().default(""),
  measurement: z.string().optional().default(""),
  countryOfOrigin: z.string().optional().default(""),
  destinationCountry: z.string().optional().default(""),
  portOfLoading: z.string().optional().default(""),
  portOfUnloading: z.string().optional().default(""),
  targetOfFumigation: z.string().optional().default(""),
  enclosureType: z.string().optional().default(""),
  doseRate: z.coerce.number().nullable().optional(),
  exposurePeriod: z.coerce.number().nullable().optional(),
  scheduleTemperature: z.coerce.number().nullable().optional(),
  appliedDose: z.coerce.number().nullable().optional(),
  appliedExposurePeriod: z.coerce.number().nullable().optional(),
  appliedTemperature: z.coerce.number().nullable().optional(),
  placeOfFumigation: z.string().optional().default(""),
  commencedAt: z.coerce.date().nullable().optional(),
  completedAt: z.coerce.date().nullable().optional(),
  finalTlvPpm: z.coerce.number().nullable().optional(),
  fullName: z.string().optional().default(""),
  accreditationNumber: z.string().optional().default(""),
  signatureDate: z.coerce.date().nullable().optional(),
  signatureUrl: z.string().optional().default(""),
});

export type TreatmentCertificateInput = z.infer<typeof treatmentCertificateSchema>;
