export interface Country {
  name: string;
  iso2: string; // ISO 3166-1 alpha-2
  iso3: string; // ISO 3166-1 alpha-3
  dialCode: string; // e.g. "+62"
  flag: string; // Emoji flag
  aliases?: string[]; // Alternate search keywords like "Turkey", "Turkiy"
}

export const PINNED_COUNTRY_CODES: string[] = ["ID", "AU", "US", "CN", "JP"];

export const COUNTRIES: Country[] = [
  { name: "Indonesia", iso2: "ID", iso3: "IDN", dialCode: "+62", flag: "🇮🇩" },
  { name: "Australia", iso2: "AU", iso3: "AUS", dialCode: "+61", flag: "🇦🇺" },
  { name: "United States", iso2: "US", iso3: "USA", dialCode: "+1", flag: "🇺🇸", aliases: ["USA", "America"] },
  { name: "China", iso2: "CN", iso3: "CHN", dialCode: "+86", flag: "🇨🇳", aliases: ["PRC"] },
  { name: "Japan", iso2: "JP", iso3: "JPN", dialCode: "+81", flag: "🇯🇵", aliases: ["Nippon"] },
  { name: "Afghanistan", iso2: "AF", iso3: "AFG", dialCode: "+93", flag: "🇦🇫" },
  { name: "Albania", iso2: "AL", iso3: "ALB", dialCode: "+355", flag: "🇦🇱" },
  { name: "Algeria", iso2: "DZ", iso3: "DZA", dialCode: "+213", flag: "🇩🇿" },
  { name: "Andorra", iso2: "AD", iso3: "AND", dialCode: "+376", flag: "🇦🇩" },
  { name: "Angola", iso2: "AO", iso3: "AGO", dialCode: "+244", flag: "🇦🇴" },
  { name: "Argentina", iso2: "AR", iso3: "ARG", dialCode: "+54", flag: "🇦🇷" },
  { name: "Armenia", iso2: "AM", iso3: "ARM", dialCode: "+374", flag: "🇦🇲" },
  { name: "Austria", iso2: "AT", iso3: "AUT", dialCode: "+43", flag: "🇦🇹" },
  { name: "Azerbaijan", iso2: "AZ", iso3: "AZE", dialCode: "+994", flag: "🇦🇿" },
  { name: "Bahamas", iso2: "BS", iso3: "BHS", dialCode: "+1-242", flag: "🇧🇸" },
  { name: "Bahrain", iso2: "BH", iso3: "BHR", dialCode: "+973", flag: "🇧🇭" },
  { name: "Bangladesh", iso2: "BD", iso3: "BGD", dialCode: "+880", flag: "🇧🇩" },
  { name: "Barbados", iso2: "BB", iso3: "BRB", dialCode: "+1-246", flag: "🇧🇧" },
  { name: "Belarus", iso2: "BY", iso3: "BLR", dialCode: "+375", flag: "🇧🇾" },
  { name: "Belgium", iso2: "BE", iso3: "BEL", dialCode: "+32", flag: "🇧🇪" },
  { name: "Belize", iso2: "BZ", iso3: "BLZ", dialCode: "+501", flag: "🇧🇿" },
  { name: "Benin", iso2: "BJ", iso3: "BEN", dialCode: "+229", flag: "🇧🇯" },
  { name: "Bhutan", iso2: "BT", iso3: "BTN", dialCode: "+975", flag: "🇧🇹" },
  { name: "Bolivia", iso2: "BO", iso3: "BOL", dialCode: "+591", flag: "🇧🇴" },
  { name: "Bosnia and Herzegovina", iso2: "BA", iso3: "BIH", dialCode: "+387", flag: "🇧🇦" },
  { name: "Botswana", iso2: "BW", iso3: "BWA", dialCode: "+267", flag: "🇧🇼" },
  { name: "Brazil", iso2: "BR", iso3: "BRA", dialCode: "+55", flag: "🇧🇷", aliases: ["Brasil"] },
  { name: "Brunei Darussalam", iso2: "BN", iso3: "BRN", dialCode: "+673", flag: "🇧🇳", aliases: ["Brunei"] },
  { name: "Bulgaria", iso2: "BG", iso3: "BGR", dialCode: "+359", flag: "🇧🇬" },
  { name: "Burkina Faso", iso2: "BF", iso3: "BFA", dialCode: "+226", flag: "🇧🇫" },
  { name: "Burundi", iso2: "BI", iso3: "BDI", dialCode: "+257", flag: "🇧🇮" },
  { name: "Cambodia", iso2: "KH", iso3: "KHM", dialCode: "+855", flag: "🇰🇭" },
  { name: "Cameroon", iso2: "CM", iso3: "CMR", dialCode: "+237", flag: "🇨🇲" },
  { name: "Canada", iso2: "CA", iso3: "CAN", dialCode: "+1", flag: "🇨🇦" },
  { name: "Cape Verde", iso2: "CV", iso3: "CPV", dialCode: "+238", flag: "🇨🇻" },
  { name: "Central African Republic", iso2: "CF", iso3: "CAF", dialCode: "+236", flag: "🇨🇫" },
  { name: "Chad", iso2: "TD", iso3: "TCD", dialCode: "+235", flag: "🇹🇩" },
  { name: "Chile", iso2: "CL", iso3: "CHL", dialCode: "+56", flag: "🇨🇱" },
  { name: "Colombia", iso2: "CO", iso3: "COL", dialCode: "+57", flag: "🇨🇴" },
  { name: "Comoros", iso2: "KM", iso3: "COM", dialCode: "+269", flag: "🇰🇲" },
  { name: "Congo (Brazzaville)", iso2: "CG", iso3: "COG", dialCode: "+242", flag: "🇨🇬" },
  { name: "Congo (Kinshasa)", iso2: "CD", iso3: "COD", dialCode: "+243", flag: "🇨🇩" },
  { name: "Costa Rica", iso2: "CR", iso3: "CRI", dialCode: "+506", flag: "🇨🇷" },
  { name: "Côte d'Ivoire", iso2: "CI", iso3: "CIV", dialCode: "+225", flag: "🇨🇮", aliases: ["Ivory Coast", "Cote d'Ivoire"] },
  { name: "Croatia", iso2: "HR", iso3: "HRV", dialCode: "+385", flag: "🇭🇷" },
  { name: "Cuba", iso2: "CU", iso3: "CUB", dialCode: "+53", flag: "🇨🇺" },
  { name: "Cyprus", iso2: "CY", iso3: "CYP", dialCode: "+357", flag: "🇨🇾" },
  { name: "Czech Republic", iso2: "CZ", iso3: "CZE", dialCode: "+420", flag: "🇨🇿", aliases: ["Czechia"] },
  { name: "Denmark", iso2: "DK", iso3: "DNK", dialCode: "+45", flag: "🇩🇰" },
  { name: "Djibouti", iso2: "DJ", iso3: "DJI", dialCode: "+253", flag: "🇩🇯" },
  { name: "Dominica", iso2: "DM", iso3: "DMA", dialCode: "+1-767", flag: "🇩🇲" },
  { name: "Dominican Republic", iso2: "DO", iso3: "DOM", dialCode: "+1-809", flag: "🇩🇴" },
  { name: "Ecuador", iso2: "EC", iso3: "ECU", dialCode: "+593", flag: "🇪🇨" },
  { name: "Egypt", iso2: "EG", iso3: "EGY", dialCode: "+20", flag: "🇪🇬" },
  { name: "El Salvador", iso2: "SV", iso3: "SLV", dialCode: "+503", flag: "🇸🇻" },
  { name: "Equatorial Guinea", iso2: "GQ", iso3: "GNQ", dialCode: "+240", flag: "🇬🇶" },
  { name: "Eritrea", iso2: "ER", iso3: "ERI", dialCode: "+291", flag: "🇪🇷" },
  { name: "Estonia", iso2: "EE", iso3: "EST", dialCode: "+372", flag: "🇪🇪" },
  { name: "Eswatini", iso2: "SZ", iso3: "SWZ", dialCode: "+268", flag: "🇸🇿", aliases: ["Swaziland"] },
  { name: "Ethiopia", iso2: "ET", iso3: "ETH", dialCode: "+251", flag: "🇪🇹" },
  { name: "Fiji", iso2: "FJ", iso3: "FJI", dialCode: "+679", flag: "🇫🇯" },
  { name: "Finland", iso2: "FI", iso3: "FIN", dialCode: "+358", flag: "🇫🇮" },
  { name: "France", iso2: "FR", iso3: "FRA", dialCode: "+33", flag: "🇫🇷" },
  { name: "Gabon", iso2: "GA", iso3: "GAB", dialCode: "+241", flag: "🇬🇦" },
  { name: "Gambia", iso2: "GM", iso3: "GMB", dialCode: "+220", flag: "🇬🇲" },
  { name: "Georgia", iso2: "GE", iso3: "GEO", dialCode: "+995", flag: "🇬🇪" },
  { name: "Germany", iso2: "DE", iso3: "DEU", dialCode: "+49", flag: "🇩🇪", aliases: ["Deutschland"] },
  { name: "Ghana", iso2: "GH", iso3: "GHA", dialCode: "+233", flag: "🇬🇭" },
  { name: "Greece", iso2: "GR", iso3: "GRC", dialCode: "+30", flag: "🇬🇷" },
  { name: "Grenada", iso2: "GD", iso3: "GRD", dialCode: "+1-473", flag: "🇬🇩" },
  { name: "Guatemala", iso2: "GT", iso3: "GTM", dialCode: "+502", flag: "🇬🇹" },
  { name: "Guinea", iso2: "GN", iso3: "GIN", dialCode: "+224", flag: "🇬🇳" },
  { name: "Guinea-Bissau", iso2: "GW", iso3: "GNB", dialCode: "+245", flag: "🇬🇼" },
  { name: "Guyana", iso2: "GY", iso3: "GUY", dialCode: "+592", flag: "🇬🇾" },
  { name: "Haiti", iso2: "HT", iso3: "HTI", dialCode: "+509", flag: "🇭🇹" },
  { name: "Honduras", iso2: "HN", iso3: "HND", dialCode: "+504", flag: "🇭🇳" },
  { name: "Hungary", iso2: "HU", iso3: "HUN", dialCode: "+36", flag: "🇭🇺" },
  { name: "Iceland", iso2: "IS", iso3: "ISL", dialCode: "+354", flag: "🇮🇸" },
  { name: "India", iso2: "IN", iso3: "IND", dialCode: "+91", flag: "🇮🇳" },
  { name: "Iran", iso2: "IR", iso3: "IRN", dialCode: "+98", flag: "🇮🇷" },
  { name: "Iraq", iso2: "IQ", iso3: "IRQ", dialCode: "+964", flag: "🇮🇶" },
  { name: "Ireland", iso2: "IE", iso3: "IRL", dialCode: "+353", flag: "🇮🇪" },
  { name: "Israel", iso2: "IL", iso3: "ISR", dialCode: "+972", flag: "🇮🇱" },
  { name: "Italy", iso2: "IT", iso3: "ITA", dialCode: "+39", flag: "🇮🇹" },
  { name: "Jamaica", iso2: "JM", iso3: "JAM", dialCode: "+1-876", flag: "🇯🇲" },
  { name: "Jordan", iso2: "JO", iso3: "JOR", dialCode: "+962", flag: "🇯🇴" },
  { name: "Kazakhstan", iso2: "KZ", iso3: "KAZ", dialCode: "+7", flag: "🇰🇿" },
  { name: "Kenya", iso2: "KE", iso3: "KEN", dialCode: "+254", flag: "🇰🇪" },
  { name: "Kiribati", iso2: "KI", iso3: "KIR", dialCode: "+686", flag: "🇰🇮" },
  { name: "Kuwait", iso2: "KW", iso3: "KWT", dialCode: "+965", flag: "🇰🇼" },
  { name: "Kyrgyzstan", iso2: "KG", iso3: "KGZ", dialCode: "+996", flag: "🇰🇬" },
  { name: "Laos", iso2: "LA", iso3: "LAO", dialCode: "+856", flag: "🇱🇦" },
  { name: "Latvia", iso2: "LV", iso3: "LVA", dialCode: "+371", flag: "🇱🇻" },
  { name: "Lebanon", iso2: "LB", iso3: "LBN", dialCode: "+961", flag: "🇱🇧" },
  { name: "Lesotho", iso2: "LS", iso3: "LSO", dialCode: "+266", flag: "🇱🇸" },
  { name: "Liberia", iso2: "LR", iso3: "LBR", dialCode: "+231", flag: "🇱🇷" },
  { name: "Libya", iso2: "LY", iso3: "LBY", dialCode: "+218", flag: "🇱🇾" },
  { name: "Liechtenstein", iso2: "LI", iso3: "LIE", dialCode: "+423", flag: "🇱🇮" },
  { name: "Lithuania", iso2: "LT", iso3: "LTU", dialCode: "+370", flag: "🇱🇹" },
  { name: "Luxembourg", iso2: "LU", iso3: "LUX", dialCode: "+352", flag: "🇱🇺" },
  { name: "Madagascar", iso2: "MG", iso3: "MDG", dialCode: "+261", flag: "🇲🇬" },
  { name: "Malawi", iso2: "MW", iso3: "MWI", dialCode: "+265", flag: "🇲🇼" },
  { name: "Malaysia", iso2: "MY", iso3: "MYS", dialCode: "+60", flag: "🇲🇾" },
  { name: "Maldives", iso2: "MV", iso3: "MDV", dialCode: "+960", flag: "🇲🇻" },
  { name: "Mali", iso2: "ML", iso3: "MLI", dialCode: "+223", flag: "🇲🇱" },
  { name: "Malta", iso2: "MT", iso3: "MLT", dialCode: "+356", flag: "🇲🇹" },
  { name: "Marshall Islands", iso2: "MH", iso3: "MHL", dialCode: "+692", flag: "🇲🇭" },
  { name: "Mauritania", iso2: "MR", iso3: "MRT", dialCode: "+222", flag: "🇲🇷" },
  { name: "Mauritius", iso2: "MU", iso3: "MUS", dialCode: "+230", flag: "🇲🇺" },
  { name: "Mexico", iso2: "MX", iso3: "MEX", dialCode: "+52", flag: "🇲🇽" },
  { name: "Micronesia", iso2: "FM", iso3: "FSM", dialCode: "+691", flag: "🇫🇲" },
  { name: "Moldova", iso2: "MD", iso3: "MDA", dialCode: "+373", flag: "🇲🇩" },
  { name: "Monaco", iso2: "MC", iso3: "MCO", dialCode: "+377", flag: "🇲🇨" },
  { name: "Mongolia", iso2: "MN", iso3: "MNG", dialCode: "+976", flag: "🇲🇳" },
  { name: "Montenegro", iso2: "ME", iso3: "MNE", dialCode: "+382", flag: "🇲🇪" },
  { name: "Morocco", iso2: "MA", iso3: "MAR", dialCode: "+212", flag: "🇲🇦" },
  { name: "Mozambique", iso2: "MZ", iso3: "MOZ", dialCode: "+258", flag: "🇲🇿" },
  { name: "Myanmar", iso2: "MM", iso3: "MMR", dialCode: "+95", flag: "🇲🇲", aliases: ["Burma"] },
  { name: "Namibia", iso2: "NA", iso3: "NAM", dialCode: "+264", flag: "🇳🇦" },
  { name: "Nauru", iso2: "NR", iso3: "NRU", dialCode: "+674", flag: "🇳🇷" },
  { name: "Nepal", iso2: "NP", iso3: "NPL", dialCode: "+977", flag: "🇳🇵" },
  { name: "Netherlands", iso2: "NL", iso3: "NLD", dialCode: "+31", flag: "🇳🇱", aliases: ["Holland"] },
  { name: "New Zealand", iso2: "NZ", iso3: "NZL", dialCode: "+64", flag: "🇳🇿" },
  { name: "Nicaragua", iso2: "NI", iso3: "NIC", dialCode: "+505", flag: "🇳🇮" },
  { name: "Niger", iso2: "NE", iso3: "NER", dialCode: "+227", flag: "🇳🇪" },
  { name: "Nigeria", iso2: "NG", iso3: "NGA", dialCode: "+234", flag: "🇳🇬" },
  { name: "North Korea", iso2: "KP", iso3: "PRK", dialCode: "+850", flag: "🇰🇵" },
  { name: "North Macedonia", iso2: "MK", iso3: "MKD", dialCode: "+389", flag: "🇲🇰", aliases: ["Macedonia"] },
  { name: "Norway", iso2: "NO", iso3: "NOR", dialCode: "+47", flag: "🇳🇴" },
  { name: "Oman", iso2: "OM", iso3: "OMN", dialCode: "+968", flag: "🇴🇲" },
  { name: "Pakistan", iso2: "PK", iso3: "PAK", dialCode: "+92", flag: "🇵🇰" },
  { name: "Palau", iso2: "PW", iso3: "PLW", dialCode: "+680", flag: "🇵🇼" },
  { name: "Palestine", iso2: "PS", iso3: "PSE", dialCode: "+970", flag: "🇵🇸" },
  { name: "Panama", iso2: "PA", iso3: "PAN", dialCode: "+507", flag: "🇵🇦" },
  { name: "Papua New Guinea", iso2: "PG", iso3: "PNG", dialCode: "+675", flag: "🇵🇬" },
  { name: "Paraguay", iso2: "PY", iso3: "PRY", dialCode: "+595", flag: "🇵🇾" },
  { name: "Peru", iso2: "PE", iso3: "PER", dialCode: "+51", flag: "🇵🇪" },
  { name: "Philippines", iso2: "PH", iso3: "PHL", dialCode: "+63", flag: "🇵🇭" },
  { name: "Poland", iso2: "PL", iso3: "POL", dialCode: "+48", flag: "🇵🇱" },
  { name: "Portugal", iso2: "PT", iso3: "PRT", dialCode: "+351", flag: "🇵🇹" },
  { name: "Qatar", iso2: "QA", iso3: "QAT", dialCode: "+974", flag: "🇶🇦" },
  { name: "Romania", iso2: "RO", iso3: "ROU", dialCode: "+40", flag: "🇷🇴" },
  { name: "Russia", iso2: "RU", iso3: "RUS", dialCode: "+7", flag: "🇷🇺", aliases: ["Russian Federation"] },
  { name: "Rwanda", iso2: "RW", iso3: "RWA", dialCode: "+250", flag: "🇷🇼" },
  { name: "Saint Kitts and Nevis", iso2: "KN", iso3: "KNA", dialCode: "+1-869", flag: "🇰🇳" },
  { name: "Saint Lucia", iso2: "LC", iso3: "LCA", dialCode: "+1-758", flag: "🇱🇨" },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", iso3: "VCT", dialCode: "+1-784", flag: "🇻🇨" },
  { name: "Samoa", iso2: "WS", iso3: "WSM", dialCode: "+685", flag: "🇼🇸" },
  { name: "San Marino", iso2: "SM", iso3: "SMR", dialCode: "+378", flag: "🇸🇲" },
  { name: "Sao Tome and Principe", iso2: "ST", iso3: "STP", dialCode: "+239", flag: "🇸🇹", aliases: ["São Tomé and Príncipe"] },
  { name: "Saudi Arabia", iso2: "SA", iso3: "SAU", dialCode: "+966", flag: "🇸🇦" },
  { name: "Senegal", iso2: "SN", iso3: "SEN", dialCode: "+221", flag: "🇸🇳" },
  { name: "Serbia", iso2: "RS", iso3: "SRB", dialCode: "+381", flag: "🇷🇸" },
  { name: "Seychelles", iso2: "SC", iso3: "SYC", dialCode: "+248", flag: "🇸🇨" },
  { name: "Sierra Leone", iso2: "SL", iso3: "SLE", dialCode: "+232", flag: "🇸🇱" },
  { name: "Singapore", iso2: "SG", iso3: "SGP", dialCode: "+65", flag: "🇸🇬" },
  { name: "Slovakia", iso2: "SK", iso3: "SVK", dialCode: "+421", flag: "🇸🇰" },
  { name: "Slovenia", iso2: "SI", iso3: "SVN", dialCode: "+386", flag: "🇸🇮" },
  { name: "Solomon Islands", iso2: "SB", iso3: "SLB", dialCode: "+677", flag: "🇸🇧" },
  { name: "Somalia", iso2: "SO", iso3: "SOM", dialCode: "+252", flag: "🇸🇴" },
  { name: "South Africa", iso2: "ZA", iso3: "ZAF", dialCode: "+27", flag: "🇿🇦" },
  { name: "South Korea", iso2: "KR", iso3: "KOR", dialCode: "+82", flag: "🇰🇷", aliases: ["Korea"] },
  { name: "South Sudan", iso2: "SS", iso3: "SSD", dialCode: "+211", flag: "🇸🇸" },
  { name: "Spain", iso2: "ES", iso3: "ESP", dialCode: "+34", flag: "🇪🇸" },
  { name: "Sri Lanka", iso2: "LK", iso3: "LKA", dialCode: "+94", flag: "🇱🇰" },
  { name: "Sudan", iso2: "SD", iso3: "SDN", dialCode: "+249", flag: "🇸🇩" },
  { name: "Suriname", iso2: "SR", iso3: "SUR", dialCode: "+597", flag: "🇸🇷" },
  { name: "Sweden", iso2: "SE", iso3: "SWE", dialCode: "+46", flag: "🇸🇪" },
  { name: "Switzerland", iso2: "CH", iso3: "CHE", dialCode: "+41", flag: "🇨🇭" },
  { name: "Syria", iso2: "SY", iso3: "SYR", dialCode: "+963", flag: "🇸🇾" },
  { name: "Taiwan", iso2: "TW", iso3: "TWN", dialCode: "+886", flag: "🇹🇼" },
  { name: "Tajikistan", iso2: "TJ", iso3: "TJK", dialCode: "+992", flag: "🇹🇯" },
  { name: "Tanzania", iso2: "TZ", iso3: "TZA", dialCode: "+255", flag: "🇹🇿" },
  { name: "Thailand", iso2: "TH", iso3: "THA", dialCode: "+66", flag: "🇹🇭" },
  { name: "Timor-Leste", iso2: "TL", iso3: "TLS", dialCode: "+670", flag: "🇹🇱", aliases: ["East Timor"] },
  { name: "Togo", iso2: "TG", iso3: "TGO", dialCode: "+228", flag: "🇹🇬" },
  { name: "Tonga", iso2: "TO", iso3: "TON", dialCode: "+676", flag: "🇹🇴" },
  { name: "Trinidad and Tobago", iso2: "TT", iso3: "TTO", dialCode: "+1-868", flag: "🇹🇹" },
  { name: "Tunisia", iso2: "TN", iso3: "TUN", dialCode: "+216", flag: "🇹🇳" },
  { name: "Turkiye", iso2: "TR", iso3: "TUR", dialCode: "+90", flag: "🇹🇷", aliases: ["Turkey", "Türkiye", "Turkiy"] },
  { name: "Turkmenistan", iso2: "TM", iso3: "TKM", dialCode: "+993", flag: "🇹🇲" },
  { name: "Tuvalu", iso2: "TV", iso3: "TUV", dialCode: "+688", flag: "🇹🇻" },
  { name: "Uganda", iso2: "UG", iso3: "UGA", dialCode: "+256", flag: "🇺🇬" },
  { name: "Ukraine", iso2: "UA", iso3: "UKR", dialCode: "+380", flag: "🇺🇦" },
  { name: "United Arab Emirates", iso2: "AE", iso3: "ARE", dialCode: "+971", flag: "🇦🇪", aliases: ["UAE", "Dubai"] },
  { name: "United Kingdom", iso2: "GB", iso3: "GBR", dialCode: "+44", flag: "🇬🇧", aliases: ["UK", "Great Britain", "England"] },
  { name: "Uruguay", iso2: "UY", iso3: "URY", dialCode: "+598", flag: "🇺🇾" },
  { name: "Uzbekistan", iso2: "UZ", iso3: "UZB", dialCode: "+998", flag: "🇺🇿" },
  { name: "Vanuatu", iso2: "VU", iso3: "VUT", dialCode: "+678", flag: "🇻🇺" },
  { name: "Vatican City", iso2: "VA", iso3: "VAT", dialCode: "+379", flag: "🇻🇦" },
  { name: "Venezuela", iso2: "VE", iso3: "VEN", dialCode: "+58", flag: "🇻🇪" },
  { name: "Vietnam", iso2: "VN", iso3: "VNM", dialCode: "+84", flag: "🇻🇳" },
  { name: "Yemen", iso2: "YE", iso3: "YEM", dialCode: "+967", flag: "🇾🇪" },
  { name: "Zambia", iso2: "ZM", iso3: "ZMB", dialCode: "+260", flag: "🇿🇲" },
  { name: "Zimbabwe", iso2: "ZW", iso3: "ZWE", dialCode: "+263", flag: "🇿🇼" },
];

/**
 * Returns list of countries sorted with pinned countries at the top.
 */
export function getSortedCountries(): { pinned: Country[]; remaining: Country[] } {
  const pinnedSet = new Set(PINNED_COUNTRY_CODES);
  const pinned: Country[] = [];
  const remaining: Country[] = [];

  // Preserve order of PINNED_COUNTRY_CODES
  PINNED_COUNTRY_CODES.forEach((code) => {
    const found = COUNTRIES.find((c) => c.iso2 === code);
    if (found) pinned.push(found);
  });

  COUNTRIES.forEach((c) => {
    if (!pinnedSet.has(c.iso2)) {
      remaining.push(c);
    }
  });

  remaining.sort((a, b) => a.name.localeCompare(b.name));

  return { pinned, remaining };
}
